BEGIN;

DROP TABLE IF EXISTS user_actions CASCADE;
DROP TABLE IF EXISTS user_stats CASCADE;
DROP TABLE IF EXISTS learning_sources CASCADE;
DROP TABLE IF EXISTS learning_items CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS learning_source_type_enum CASCADE;
DROP TYPE IF EXISTS user_stat_status_enum CASCADE;
DROP TYPE IF EXISTS user_action_type_enum CASCADE;

COMMIT;
