// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a simplified version - regenerate with: make proto

package pb

import (
	"context"

	"google.golang.org/grpc"
)

// UwuServiceClient is the client API for UwuService service.
type UwuServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetExample(ctx context.Context, in *GetExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error)
	CreateExample(ctx context.Context, in *CreateExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	StreamChat(ctx context.Context, opts ...grpc.CallOption) (UwuService_StreamChatClient, error)
}

type uwuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUwuServiceClient(cc grpc.ClientConnInterface) UwuServiceClient {
	return &uwuServiceClient{cc}
}

func (c *uwuServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/uwu.v1.UwuService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uwuServiceClient) GetExample(ctx context.Context, in *GetExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error) {
	out := new(ExampleResponse)
	err := c.cc.Invoke(ctx, "/uwu.v1.UwuService/GetExample", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uwuServiceClient) CreateExample(ctx context.Context, in *CreateExampleRequest, opts ...grpc.CallOption) (*ExampleResponse, error) {
	out := new(ExampleResponse)
	err := c.cc.Invoke(ctx, "/uwu.v1.UwuService/CreateExample", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uwuServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, "/uwu.v1.UwuService/Chat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uwuServiceClient) StreamChat(ctx context.Context, opts ...grpc.CallOption) (UwuService_StreamChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &UwuService_ServiceDesc.Streams[0], "/uwu.v1.UwuService/StreamChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &uwuServiceStreamChatClient{stream}
	return x, nil
}

type UwuService_StreamChatClient interface {
	Send(*ChatRequest) error
	Recv() (*ChatResponse, error)
	grpc.ClientStream
}

type uwuServiceStreamChatClient struct {
	grpc.ClientStream
}

func (x *uwuServiceStreamChatClient) Send(m *ChatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uwuServiceStreamChatClient) Recv() (*ChatResponse, error) {
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UwuServiceServer is the server API for UwuService service.
type UwuServiceServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetExample(context.Context, *GetExampleRequest) (*ExampleResponse, error)
	CreateExample(context.Context, *CreateExampleRequest) (*ExampleResponse, error)
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	StreamChat(UwuService_StreamChatServer) error
	mustEmbedUnimplementedUwuServiceServer()
}

// UnimplementedUwuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUwuServiceServer struct{}

func (UnimplementedUwuServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, nil
}

func (UnimplementedUwuServiceServer) GetExample(context.Context, *GetExampleRequest) (*ExampleResponse, error) {
	return nil, nil
}

func (UnimplementedUwuServiceServer) CreateExample(context.Context, *CreateExampleRequest) (*ExampleResponse, error) {
	return nil, nil
}

func (UnimplementedUwuServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, nil
}

func (UnimplementedUwuServiceServer) StreamChat(UwuService_StreamChatServer) error {
	return nil
}

func (UnimplementedUwuServiceServer) mustEmbedUnimplementedUwuServiceServer() {}

type UwuService_StreamChatServer interface {
	Send(*ChatResponse) error
	Recv() (*ChatRequest, error)
	grpc.ServerStream
}

type uwuServiceStreamChatServer struct {
	grpc.ServerStream
}

func (x *uwuServiceStreamChatServer) Send(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uwuServiceStreamChatServer) Recv() (*ChatRequest, error) {
	m := new(ChatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterUwuServiceServer(s grpc.ServiceRegistrar, srv UwuServiceServer) {
	s.RegisterService(&UwuService_ServiceDesc, srv)
}

var UwuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uwu.v1.UwuService",
	HandlerType: (*UwuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "HealthCheck", Handler: _UwuService_HealthCheck_Handler},
		{MethodName: "GetExample", Handler: _UwuService_GetExample_Handler},
		{MethodName: "CreateExample", Handler: _UwuService_CreateExample_Handler},
		{MethodName: "Chat", Handler: _UwuService_Chat_Handler},
	},
	Streams: []grpc.StreamDesc{
		{StreamName: "StreamChat", Handler: _UwuService_StreamChat_Handler, ServerStreams: true, ClientStreams: true},
	},
	Metadata: "service.proto",
}

func _UwuService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UwuServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/uwu.v1.UwuService/HealthCheck"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UwuServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	})
}

func _UwuService_GetExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UwuServiceServer).GetExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/uwu.v1.UwuService/GetExample"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UwuServiceServer).GetExample(ctx, req.(*GetExampleRequest))
	})
}

func _UwuService_CreateExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExampleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UwuServiceServer).CreateExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/uwu.v1.UwuService/CreateExample"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UwuServiceServer).CreateExample(ctx, req.(*CreateExampleRequest))
	})
}

func _UwuService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UwuServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/uwu.v1.UwuService/Chat"}
	return interceptor(ctx, in, info, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UwuServiceServer).Chat(ctx, req.(*ChatRequest))
	})
}

func _UwuService_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UwuServiceServer).StreamChat(&uwuServiceStreamChatServer{stream})
}
