// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified version - regenerate with: make proto

package pb

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

type HealthCheckRequest struct{}

type HealthCheckResponse struct {
	Status  HealthCheckResponse_ServingStatus
	Service string
}

type GetExampleRequest struct {
	Id string
}

type CreateExampleRequest struct {
	Name        string
	Description string
}

type ExampleResponse struct {
	Id          string
	Name        string
	Description string
	CreatedAt   int64
	UpdatedAt   int64
}

type ChatRequest struct {
	Message  string
	Provider string
	History  []*ChatMessage
}

type ChatMessage struct {
	Role    string
	Content string
}

type ChatResponse struct {
	Response string
	Provider string
}
